### ISSUE TITLE
Provide a way of serializing and deseriaizing a enum number

### ISSUE THREAD

**Issue by vityafx** [vityafx/serde-aux#1]
Enum with numbers are not supported by the serde. This is usually done with implementing a macro. This crate could have such a procedural macro which could generate everything on the fly.

**Comment by vityafx** [comment]
Done #25b0fb00341cfb78f2a56e5889c960726a408639

**Comment by vityafx** [comment]
Procedural macro still needs to be written.

**Comment by naftulikay** [comment]
It seems to be implemented, but serialize is somehow missing.

**Comment by vityafx** [comment]
@naftulikay yes, you're right, I forgot the serialization part. Gonna be there soon.

**Comment by vityafx** [comment]
Added serialize in [`0.5.3`](https://docs.rs/serde-aux/0.5.3/serde_aux/).

**Comment by naftulikay** [comment]
Thanks so much!
