### ISSUE TITLE
deserialize_struct_case_insensitive + serde::rename

### ISSUE THREAD

**Issue by stanislav-tkach** [vityafx/serde-aux#8]
I have encountered strange behavior when `deserialize_struct_case_insensitive` is used in conjunction with `serde::rename`. Here is a slightly modified example taken from the `deserialize_struct_case_insensitive` documentation:
```rust
use serde::Deserialize;
use serde_aux::prelude::*;

#[derive(Deserialize, Debug)]
struct AnotherStruct {
    #[serde(rename = "fieldname")] 
    field_name: String,
}
#[derive(Deserialize, Debug)]
struct MyStruct {
    #[serde(deserialize_with = "deserialize_struct_case_insensitive")]
    another_struct: AnotherStruct,
}

fn main() {
    let s = r#"{ "another_struct": { "FiElDnAmE": "Test example" } }"#;
    let a: MyStruct = serde_json::from_str(s).unwrap();
    assert_eq!(a.another_struct.field_name, "Test example");
}
```
In this case everything works as expected, but if `#[serde(rename = "fieldname")] ` is changed to `#[serde(rename = "fieldName")] ` then I get the following error:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `fieldName`", line: 1, column: 53)', src/main.rs:17:47

**Comment by vityafx** [comment]
In the `serde-aux` it is impossible to do, unfortunately. I pass a lower-cased string to serde so that it handles all the stuff after. So if I change a field name there and pass it to serde which is instructed to parse a field with a `rename`, it simply won't work.

**Comment by stanislav-tkach** [comment]
Thanks for the quick response! I expected that this issue couldn't be fixed outside of serde. Perhaps documentation can mention this pitfall?

**Comment by vityafx** [comment]
> Thanks for the quick response! I expected that this issue couldn't be fixed outside of serde. Perhaps documentation can mention this pitfall?

Sure thing. Thanks for the suggestion.

**Comment by vityafx** [comment]
Released a version with a documentation note: https://docs.rs/serde-aux/1.0.1/serde_aux/container_attributes/fn.deserialize_struct_case_insensitive.html#notes

If I find out I can do anything else to make this work, I'll comment on this issue and reopen it.
